#include <signal.h>
#include <stdio.h>
#include <unistd.h>
#include <inttypes.h>
#include <getopt.h>
#include "server.hpp"
#include "sockets.hpp"
#include "blocks.hpp"
#include "commands.hpp"
#include "util.hpp"
#include "config.hpp"
#include "log.hpp"
